services:
  - type: web
    name: futebol-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
